// Generated by CoffeeScript 1.7.1
(function() {
  var MapTrigger, trigger;

  MapTrigger = (function() {
    function MapTrigger(trigger, map) {
      console.log(trigger);
      $(trigger).on("mouseover", function() {
        map.css("background-size", "110% 110%");
        return map.css("z-index", "1");
      });
      $(trigger).on("mouseout", function() {
        map.css("background-size", "100% 100%");
        return map.css("z-index", "0");
      });
    }

    return MapTrigger;

  })();

  trigger = new MapTrigger($(".map-labels #toronto"), $(".image-map #toronto"));

  trigger = new MapTrigger($(".map-labels #durham"), $(".image-map #durham"));

  trigger = new MapTrigger($(".map-labels #peel"), $(".image-map #peel"));

  trigger = new MapTrigger($(".map-labels #york"), $(".image-map #york"));

  trigger = new MapTrigger($(".map-labels #halton"), $(".image-map #halton"));

}).call(this);
